language: node_js

node_js:
  - "12.4.0"

cache: yarn

install:
  - yarn global add lerna jest
  - lerna bootstrap

# matrix:
#   include:
#     - name: "App Pipeline"
#       env: 
#         - PACKAGE_LOCATION=packages/app
#         - PACAKGE_NAME=home
#     - name: "Login Pipeline"
#       env: 
#         - PACKAGE_LOCATION=packages/login
#         - PACAKGE_NAME=login

# - cd $PACKAGE_LOCATION
script:
  - yarn build
